name: Deploy all contracts
on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Profile'
        required: true
        default: 'testnet'
        type: choice
        options:
        - testnet
        - mainnet

      alias:
        description: 'Account alias'
        required: true
        default: 'carbonable'
        type: choice
        options:
        - carbonable

      wallet:
        description: 'Wallet type'
        required: true
        default: 'starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount'
        type: choice
        options:
        - starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount
        
      project:
        description: 'Carbonable project inputs (;-sep)'
        default: 'name;symbol'
        required: false
        type: string

permissions:
  contents: read

jobs:
  parser:
    runs-on: ubuntu-latest
    outputs:
      project_name: ${{ steps.project.outputs.name }}
      project_symbol: ${{ steps.project.outputs.symbol }}
    steps:
      - name: Parse project
        id: project
        run: |
          IFS=';' read -ra args <<< "${{ inputs.project }}"
          echo "::set-output name=name::${args[0]}"
          echo "::set-output name=symbol::${args[1]}"

  project:
    needs: parser
    uses: ./.github/workflows/deploy_project.yml
    with:
      profile: ${{ inputs.profile }}
      alias: ${{ inputs.alias }}
      wallet: ${{ inputs.wallet }}
      project_name: ${{ needs.parser.outputs.project_name }}
      project_symbol: ${{ needs.parser.outputs.project_symbol }}
    secrets: inherit

  log:
    runs-on: ubuntu-latest
    needs: project
    steps:
    - run: echo ${{ needs.project.outputs.contract_address }}

    