name: Build and deploy contracts to testnet

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'testnet'
        type: choice
        options:
        - testnet
        - mainnet

      alias:
        description: 'Account alias'
        required: true
        default: 'carbonable'
        type: choice
        options:
        - carbonable

      wallet:
        description: 'Wallet type'
        required: true
        default: 'starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount'
        type: choice
        options:
        - starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount

      deploy_project:
        description: 'Deploy Carbonable project'
        required: true
        default: true
        type: boolean 
      project_name:
        description: 'Carbonable project name'
        default: 'Carbonable ERC-721 Test'
        required: true
        type: string 
      project_symbol:
        description: 'Carbonable project symbol'
        default: 'CET'
        required: true
        type: string

      transfer_ownership:
        description: 'Transfer project ownership to minter'
        required: true
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash -s -- -v $PROTOSTAR_VERSION
        env:
          PROTOSTAR_VERSION: ${{ secrets.protostar_version }}

      - name: Update env variables
        run: source /home/runner/.bashrc | bash

      - name: Install protostar dependencies
        run: /home/runner/.protostar/dist/protostar/protostar install
        
      - name: Compile smart contracts
        run: /home/runner/.protostar/dist/protostar/protostar build

      - name: Setup admin account
        run: |
          mkdir /home/runner/.starknet_accounts && \
          echo "$ACCOUNT" > "/home/runner/.starknet_accounts/starknet_open_zeppelin_accounts.json"
        env:
          ACCOUNT: ${{ secrets.ADMIN_ACCOUNT }}

      - name: Load deployement tools
        run: |
          source ./scripts/utils.sh
          source ./scripts/logging.sh
          source ./scripts/tools.sh

      - name: Deploy carbonable project contract
        run: |
          /home/runner/.protostar/dist/protostar/protostar \
          --profile ${{ inputs.network }} \
          deploy ./build/CarbonableProject.json \
          --inputs \
            $(str_to_felt ${{ inputs.project_name }}) \
            $(str_to_felt ${{ inputs.project_symbol }}) \
            $(get_account_address ${{ inputs.alias }} "/home/runner/.starknet_accounts/starknet_open_zeppelin_accounts.json")
        env:
          NETWORK: ${{ inputs.network }}
          STARKNET_WALLET: ${{ inputs.wallet }}
          PROJECT_NAME: $(str_to_felt ${{ inputs.project_name }})
          PROJECT_SYMBOL: $(str_to_felt ${{ inputs.project_symbol }})
          ADMIN_ADDRESS: $(get_account_address ${{ inputs.alias }} "/home/runner/.starknet_accounts/starknet_open_zeppelin_accounts.json")