name: Deploy all contracts
on:
  workflow_dispatch:
    inputs:
      profile:
        description: 'Profile'
        required: true
        default: 'testnet'
        type: choice
        options:
        - testnet
        - mainnet

      alias:
        description: 'Account alias'
        required: true
        default: 'carbonable'
        type: choice
        options:
        - carbonable

      wallet:
        description: 'Wallet type'
        required: true
        default: 'starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount'
        type: choice
        options:
        - starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount
        
      project_name:
        description: 'Carbonable project name'
        default: 'Carbonable ERC-721 Test'
        required: true
        type: string

      project_symbol:
        description: 'Carbonable project symbol'
        default: 'CET'
        required: true
        type: string

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy_project.yml@main
    with:
      profile: {{ inputs.profile }}
      alias: {{ inputs.alias }}
      wallet: {{ inputs.wallet }}
      project_name: {{ inputs.project_name }}
      project_symbol: {{ inputs.project_symbol }}

  log:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - run: echo ${{ needs.deploy.outputs.contract_address }}

    