name: Build and deploy contracts to testnet

on:
  workflow_dispatch:
    inputs:
      network:
        description: 'Network'
        required: true
        default: 'testnet'
        type: choice
        options:
        - testnet
        - mainnet

      alias:
        description: 'Account alias'
        required: true
        default: 'carbonable'
        type: choice
        options:
        - carbonable

      wallet:
        description: 'Wallet type'
        required: true
        default: 'starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount'
        type: choice
        options:
        - starkware.starknet.wallets.open_zeppelin.OpenZeppelinAccount

      deploy_project:
        description: 'Deploy Carbonable project'
        required: true
        default: true
        type: boolean 
      project_name:
        description: 'Carbonable project name'
        default: 'Carbonable ERC-721 Test'
        required: true
        type: string 
      project_symbol:
        description: 'Carbonable project symbol'
        default: 'CET'
        required: true
        type: string 

      deploy_minter:
        description: 'Deploy Carbonable minter'
        required: true
        default: true
        type: boolean
      minter_payment_token:
        description: 'Payment token address'
        default: '0x07394cbe418daa16e42b87ba67372d4ab4a5df0b05c6e554d158458ce245bc10'
        required: true
        type: string
      minter_public_sale_open:
        description: 'Public sale open'
        default: false
        required: true
        type: boolean
      minter_max_buy_per_tx:
        description: 'Max buy per tx'
        default: '5'
        required: true
        type: string
      minter_unit_price:
        description: 'Unit price'
        default: '10'
        required: true
        type: string
      minter_max_supply_for_mint:
        description: 'Max supply for mint'
        default: '10'
        required: true
        type: string
      minter_reserved_supply_for_mint:
        description: 'Reserved supply for mint'
        default: '3'
        required: true
        type: string

      transfer_ownership:
        description: 'Transfer project ownership to minter'
        required: true
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install protostar
        run: |
          curl -L https://raw.githubusercontent.com/software-mansion/protostar/master/install.sh | bash -s -- -v $PROTOSTAR_VERSION
        env:
          PROTOSTAR_VERSION: ${{ secrets.protostar_version }}

      - name: Update env variables
        run: source /home/runner/.bashrc | bash

      - name: Install protostar dependencies
        run: /home/runner/.protostar/dist/protostar/protostar install
        
      - name: Compile smart contracts
        run: /home/runner/.protostar/dist/protostar/protostar build

      - name: Setup admin account
        run: |
          mkdir /home/runner/.starknet_accounts && \
          echo "$ACCOUNT" > "/home/runner/.starknet_accounts/starknet_open_zeppelin_accounts.json"
        env:
          ACCOUNT: ${{ secrets.ADMIN_ACCOUNT }}

      - name: Load deployement tools
        run: |
          source ./scripts/utils.sh
          source ./scripts/logging.sh
          source ./scripts/tools.sh

      - name: Deploy carbonable project contract
        run: |
          /home/runner/.protostar/dist/protostar/protostar \
          --profile $NETWORK \
          deploy ./build/CarbonableProject.json \
          --inputs $PROJECT_NAME $PROJECT_SYMBOL $ADMIN_ADDRESS
        env:
          NETWORK: ${{ inputs.network }}
          STARKNET_WALLET: ${{ inputs.wallet }}
          PROJECT_NAME: $(str_to_felt ${{ inputs.project_name }})
          PROJECT_SYMBOL: $(str_to_felt ${{ inputs.project_symbol }})
          ADMIN_ADDRESS: $(get_account_address ${{ inputs.alias }} "/home/runner/.starknet_accounts/starknet_open_zeppelin_accounts.json")